branches:
  only:
    - master
    - develop

dist: xenial

addons:
  apt:
    packages:
      - build-essential
      - curl
      - libltdl7
      - git

services:
  - docker

language: node_js
node_js: '10'

cache:
  timeout: 604800 # 7 days
  directories:
    - "$HOME/.npm"

env:
  global:
    - TEST_NODE=http://localhost:3013
    - TEST_URL=http://localhost:3013
    - TEST_DEBUG_URL=http://localhost:3113
    - TEST_WS_URL=ws://localhost:3014/channel
    - TEST_NETWORK_ID=ae_devnet
    - COMPILER_URL=http://localhost:3080
    - FORCE_COMPATIBILITY=false

before_install:
  - docker-compose up -d node compiler

install:
  - npm ci

jobs:
  include:
  - stage: Tests
    if: type != "cron"
    name: Test AENS
    script:
    - npm run test-aens
    after_success:
    - npm run report-coverage
  - stage: Tests
    if: type != "cron"
    name: Test Channel
    script:
    - npm run test-channel
    after_success:
    - npm run report-coverage
  - stage: Tests
    if: type != "cron"
    name: Test Contract, Node, Oracle, Account and else
    script:
    - npm run test-else
    after_success:
    - npm run report-coverage
  - stage: Tests
    if: type = "cron"
    env:
    - NODE_TAG=master
    - COMPILER_TAG=latest
    - FORCE_COMPATIBILITY=true
    script:
    - npm run test
    after_success:
    - npm run report-coverage
  - stage: Deploy Next Release
    if: type != "cron"
    before_deploy:
      - npm run build
    deploy:
      provider: npm
      tag: next
      on:
        branch: develop
        condition: type != "cron"
      email: $NPM_EMAIL
      api_key:
        secure: $NPM_AUTH_TOKEN
