dist: bionic
language: node_js
node_js: 12

services:
  - docker

before_install:
  - if [[ $TRAVIS_EVENT_TYPE == "cron" ]]; then
      export NODE_TAG=master;
      export COMPILER_TAG=latest;
      export FORCE_COMPATIBILITY=true;
    fi
  - if [[ $TRAVIS_BUILD_STAGE_NAME == "Integration tests" ]]; then
      docker-compose up -d;
    fi

install: npm ci --ignore-scripts

jobs:
  include:
    - stage: Tests
      script:
        - npm run lint
        - npm run build
        - npm run test:unit
        - npm run report-coverage
    - stage: Integration tests
      name: Channel, accounts
      script:
        - npm run test:integration:channel,accounts
        - npm run report-coverage
    - name: Contract, chain
      script:
        - npm run test:integration:contract,chain
        - npm run report-coverage
    - name: Else
      script:
        - npm run test:integration:else
        - npm run report-coverage
