---
peers: []
  # - aenode://pp_HdcpgTX2C1aZ5sjGGysFEuup67K9XiFsWqSPJs4RahEcSyF7X@sync.sdk-testnet.aepps.com:3015
  # - aenode://pp_HdcpgTX2C1aZ5sjGGysFEuup67K9XiFsWqSPJs4RahEcSyF7X@localhost:3016
#- aenode://pp_HdcpgTX2C1aZ5sjGGysFEuup67K9XiFsWqSPJs4RahEcSyF7X@af5621d1de36f11e8bb0b1215f72bd59-742041481.us-east-1.elb.amazonaws.com:3015

http:
  external:
    port: 3013
  internal:
    debug_endpoints: true
    port: 3113
    listen_address: 0.0.0.0
#  endpoints:
#    debug: true
#  debug: true


websocket:
  channel:
    listen_address: 0.0.0.0
    port: 3014

keys:
  peer_password: "top secret"
  dir: ./keys

chain:
  persist: true

mining:
  autostart: true
  beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"
  expected_mine_rate: 4000
  micro_block_cycle: 1000
  cuckoo:
    miner:
      executable: mean15-generic
      extra_args: ""
      edge_bits: 15

fork_management:
  network_id: "ae_devnet"
